Models/ErrorViewModel.cs
namespace AutosWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AutosController.cs
using BLLAUTOS;
using BLLAUTOS.Services.Contracts;
using DALAUTOS.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AutosWeb.Controllers
{
    public class AutosController: Controller
    {
        //AutosBLL _BLLAutos = new AutosBLL();
        //MarcasBLL _marcasBLL = new MarcasBLL();
        //ColorBLL _colorBLL = new ColorBLL();
        //ModelosBLL _modelosBLL = new ModelosBLL();

        private readonly IServiceAutos _serviceAutos;
        //private readonly IServiceMarcas _serviceMarcas;
        //private readonly IServiceColor _serviceColor;
        //private readonly IServiceModelo _serviceModelo;

        public AutosController(IServiceAutos? serviceAutos)
        {
            _serviceAutos = serviceAutos;
            //_serviceMarcas = serviceMarcas;
            //_serviceColor = serviceColor;
            //_serviceModelo = serviceModelo;
        }

        public IActionResult VerAutos(string placas,int page)
        {
            var autos = _serviceAutos.GetAutos();
            if (!string.IsNullOrEmpty(placas))
            {
                return View(_serviceAutos.GetAutos().Where(a => a.Placas.Contains(placas)).ToList());
            }
            ViewBag.CurrentPage = page;
            if (page != 0 && _serviceAutos.GetAutosPaginated(page, 12).Count>0)
            {
                return View(_serviceAutos.GetAutosPaginated(page, 12));
            }
            else
            {
                ViewBag.CurrentPage = 1;
                return View(_serviceAutos.GetAutosPaginated(1, 12));
               
            }
            return View(autos);
        }

        public IActionResult CrearAuto()
        {
            //ViewBag.MarcaId = new SelectList(_serviceMarcas.GetMarcas(), "Id", "NMarca");
            //ViewBag.ColorId = new SelectList(_serviceColor.GetColors(), "Id", "NColor");
            return View();
        }

        public IActionResult DetallesDeAuto(int Id)
        {
            return View(_serviceAutos.GetAutoById(Id));
        }

        public IActionResult EditarAuto(int Id)
        {
            //ViewBag.MarcaId = new SelectList(_marcasBLL.GetMarcas(), "Id", "NMarca");
            //ViewBag.ColorId = new SelectList(_colorBLL.GetColors(), "Id", "NColor");
            return View(_serviceAutos.GetAutoById(Id));
        }

        public IActionResult BorrarAuto(int Id)
        {
            return View(_serviceAutos.GetAutoById(Id));
        }

        public IActionResult ConfirmacionBorrar(int Id)
        {
            _serviceAutos.EliminarAuto(Id);
            return RedirectToAction("VerAutos");
        }
        [HttpPost]
        public IActionResult CrearAuto(Auto auto)
        {
            if(auto.ColorId !=null&& auto.MarcaId!=null)
            {
                var color = _serviceAutos.ObtenerColor(auto.ColorId);
                var marca = _serviceAutos.GetMarcaName(auto.MarcaId);
                auto.Placas = $"{marca.ToUpper()[0]}{color.ToUpper()[0]}{_serviceAutos.GetAutos().Count.ToString().PadLeft(3, '0')}";
            }
            _serviceAutos.CrearAuto(auto);
            return RedirectToAction("VerAutos");
        }

        [HttpPost]
        public IActionResult EditarAuto(Auto auto)
        {

            _serviceAutos.EditarAuto(auto);
            return RedirectToAction("VerAutos");
        }

        [HttpGet]
        public IActionResult GetModelosByMarca(int marcaId)
        {
            var modelos = _serviceAutos.GetModelosByMarca(marcaId);

            // Retornar los modelos en formato JSON
            return Json(modelos);
        }

        [HttpGet]
        public IActionResult GetModeloById(int modeloId)
        {
            var modelos = _serviceAutos.GetModeloById(modeloId);

            // Retornar los modelos en formato JSON
                return Json(modelos);
        }

        [HttpGet]
        public IActionResult GetMarcas()
        {
            var marcas = _serviceAutos.GetMarcas();

            return Json(marcas);
        }
        [HttpGet]
        public IActionResult GetColores()
        {
            var colores = _serviceAutos.GetColors();

            return Json(colores);
        }
    }
}

Controllers/HomeController.cs
using AutosWeb.Models;
using DALAUTOS.Model;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AutosWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

Views/Autos/BorrarAuto.cshtml
@model DALAUTOS.Model.Auto

@{
    ViewData["Title"] = "BorrarAuto";
}

<h1>Borrar Auto</h1>

<h3>Seguro que desea eliminar este auto?</h3>
<div class="d-flex justify-content-center">
    <br />
    <div class="col-sm-6">
        <div class="card" style="width: 18rem; position: relative;">
            <img src="@Model.Marca.Logo" alt="Logo" class="logo-img">
            <img class="card-img-top fixed-size-img" src="@Model.Modelo.Foto" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@Model.Modelo.Name</h5>
                <h6 class="card-title">@Model.Placas</h6>
                <br>
                @Html.DisplayFor(modelItem => Model.status) status
                <br>
                <p class="card-text">@Model.Color.NColor - @Model.year</p>
            </div>
            <div class="card-footer">
                <form asp-action="BorrarAuto">
                    <input type="hidden" asp-for="Id" />
                    <a asp-action="ConfirmacionBorrar" asp-controller="Autos" asp-route-id="@Model.Id" class="btn btn-danger">Eliminar</a>
                    <br />
                    <a asp-action="VerAutos" asp-route-page="1">Volver</a>
                </form>
            </div>
        </div>
    </div>
    <br />  
</div>

<style>
    .logo-img {
        position: absolute;
        top: 10px;
        right: 10px;
        width: 40px;
        height: 40px;
    }

    .fixed-size-img {
        width: 100%;
        height: 200px; /* Ajusta la altura deseada */
        object-fit: cover;
    }
</style>

Views/Autos/CrearAuto.cshtml
@using BLLAUTOS;
@model DALAUTOS.Model.Auto

@{
    ViewData["Title"] = "CrearAuto";
    //ColorBLL _colorBLL = new ColorBLL();
    //MarcasBLL _marcasBLL = new MarcasBLL();
    //ModelosBLL _modelosBLL = new ModelosBLL();
    //var marcas = await _marcasBLL.GetMarcasAsync();
    //var colores = await _colorBLL.GetColorsAsync();
    //var modelos = await _modelosBLL.GetModelosAsync();
}

<h1>Crear Auto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearAuto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label">Marca</label>
                <select id="marca-select" asp-for="MarcaId" class="form-control">
                  @*  @foreach (var marca in marcas)
                    {
                        <option value="@marca.Id">@marca.NMarca</option>
                    }*@
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ColorId" class="control-label">Color</label>
                <select id="color-select" asp-for="ColorId" class="form-control">
                    @*@foreach (var color in colores)
                    {
                        <option value="@color.Id">@color.NColor</option>
                    }*@
                </select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="status" /> @Html.DisplayNameFor(model => model.status)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label">Año</label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloId" class="control-label">Modelo</label>
                <select id="modelo-select" asp-for="ModeloId" class="form-control">
                    @*@foreach (var modelo in modelos)
                    {
                        <option value="@modelo.Id">@modelo.Name</option>
                    }*@
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" alt="Seleccione un auto" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <img src="" width="800" height="600" id="Image-Auto" />
    </div>
</div>

<div>
    <a asp-action="VerAutos">Voler</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    var marcaSelect = document.getElementById("marca-select");
    var modeloSelect = document.getElementById("modelo-select");
    var imagenauto = document.getElementById("Image-Auto");
    var colorSelect = document.getElementById("color-select")

    marcaSelect.addEventListener("change", function () {
        updateImage();
    });

    modeloSelect.addEventListener("change", function () {
        var modeloId = modeloSelect.value;
        var url = "/Autos/GetModeloById?modeloId=" + modeloId;

        fetch(url)
            .then(response => response.json())
            .then(data => {
                imagenauto.src = data;
            })
            .catch(error => console.log(error));
    });

    window.onload = function () {
        getModels();
        getColores();
    }

    function updateImage() {
        var marcaId = marcaSelect.value;
        var url = "/Autos/GetModelosByMarca?marcaId=" + marcaId;

        fetch(url)
            .then(response => response.json())
            .then(data => {
                modeloSelect.innerHTML = "";

                data.forEach(function (modelo) {
                    var option = document.createElement("option");
                    option.value = modelo.id;
                    option.text = modelo.name;
                    modeloSelect.appendChild(option);


                    var modeloId = modeloSelect.value;
                    var url = "/Autos/GetModeloById?modeloId=" + modeloId;

                    fetch(url)
                        .then(response => response.json())
                        .then(data => {
                            imagenauto.src = data;
                        })
                        .catch(error => console.log(error))
                });
            })
            .catch(error => console.log(error));
    }

    function getModels() {
        var url = "/Autos/GetMarcas";

        fetch(url)
            .then(response => response.json())
            .then(data => {
                data.forEach(function (marca) {
                    var option = document.createElement("option");
                    option.value = marca.id;
                    option.text = marca.nMarca;
                    marcaSelect.appendChild(option);
                    updateImage();
                });
            })
    }

    function getColores(){
        var url = "/Autos/GetColores";

        fetch(url)
            .then(response => response.json())
            .then(data => {
                data.forEach(function (color) {
                    var option = document.createElement("option");
                    option.value = color.id;
                    option.text = color.nColor;
                    colorSelect.appendChild(option)
                });
            })
    }
</script>

Views/Autos/EditarAuto.cshtml
@using BLLAUTOS;
@using BLLAUTOS.Services.Contracts;
@model DALAUTOS.Model.Auto

@{
    ViewData["Title"] = "EditarAuto";
    //ColorBLL _colorBLL = new ColorBLL();
    //MarcasBLL _marcasBLL = new MarcasBLL();
    //ModelosBLL _modelosBLL = new ModelosBLL();
    //var marcas = await _marcasBLL.GetMarcasAsync();
    //var colores = await _colorBLL.GetColorsAsync();
    //var modelos = await _modelosBLL.GetModelosAsync();

    //IServiceModelo _serviceModelo;
    //var modelos = await _serviceModelo.GetModelosAsync();


}

<h1>Editar Auto</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarAuto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label">Marca</label>
                <select id="marca-select" asp-for="MarcaId" class="form-control">
                    @*@foreach (var marca in marcas)
                    {*@
                        <option value="@Model.Marca.Id">@Model.Marca.NMarca</option>
                    @*}*@
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ColorId" class="control-label">Color</label>
                <select asp-for="ColorId" class="form-control">
                    @*@foreach (var color in colores)
                    {*@
                        <option value="@Model.Color.Id">@Model.Color.NColor</option>
                    @*}*@
                </select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="status" /> @Html.DisplayNameFor(model => model.status)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label">Año</label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloId" class="control-label">Modelo</label>
                <select id="modelo-select" asp-for="ModeloId" class="form-control">
                    @*@foreach (var modelo in modelos)
                    {*@
                            <option value="@Model.Modelo.Id">@Model.Modelo.Name</option>
                   @* }*@
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <img src="@Model.Modelo.Foto" width="800" height="600" id="Image-Auto" class="img-auto"/>
    </div>
</div>

<style>
    .img-auto:hover{
        transform: scale(1.2);
        transition: transform 0.3s ease; 
    }
</style>

<div>
    <a asp-action="VerAutos" asp-route-page="1">Volver</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

<script>
    var marcaSelect = document.getElementById("marca-select");
    var modeloSelect = document.getElementById("modelo-select");
    var imagenauto = document.getElementById("Image-Auto");

    marcaSelect.addEventListener("change", function(){
        updateImageN();
    });

    modeloSelect.addEventListener("change", function () {
        var modeloId = modeloSelect.value;
        var url = "/Autos/GetModeloById?modeloId=" + modeloId;

        fetch(url)
            .then(response => response.json())
            .then(data => {
                imagenauto.src = data;
            })
            .catch(error => console.log(error));
    });

    window.onload = function () {
        getModels();
        updateImage();
    };
        
        function updateImage(){
            var marcaId = marcaSelect.value;
            var url = "/Autos/GetModelosByMarca?marcaId=" + marcaId;

            fetch(url)
                .then(response => response.json())
                .then(data => {
                    modeloSelect.innerHTML = "";

                    data.forEach(function (modelo) {
                        var option = document.createElement("option");
                        option.value = modelo.id;
                        option.text = modelo.name;
                        modeloSelect.appendChild(option);

                    var selectedModeloId = @Model.ModeloId;

                    for (var i = 0; i < modeloSelect.options.length; i++) {
                        if (modeloSelect.options[i].value == selectedModeloId) {
                            modeloSelect.selectedIndex = i;
                            break;
                        }
                    }
                        var modeloId = modeloSelect.value;
                        var url = "/Autos/GetModeloById?modeloId=" + @Model.Modelo.Id;

                        fetch(url)
                            .then(response => response.json())
                            .then(data => {
                                imagenauto.src = data;
                            })
                            .catch(error => console.log(error))
                    });
                })
                .catch(error => console.log(error));
        }

        function getModels(){
        var url = "/Autos/GetMarcas";

        fetch(url)
            .then(response => response.json())
            .then(data => {
                data.forEach(function(marca){
                    var option = document.createElement("option");
                    option.value = marca.id;
                    option.text = marca.nMarca;
                    marcaSelect.appendChild(option);
                });
            })
        }


    function updateImageN() {
        var marcaId = marcaSelect.value;
        var url = "/Autos/GetModelosByMarca?marcaId=" + marcaId;

        fetch(url)
            .then(response => response.json())
            .then(data => {
                modeloSelect.innerHTML = "";

                data.forEach(function (modelo) {
                    var option = document.createElement("option");
                    option.value = modelo.id;
                    option.text = modelo.name;
                    modeloSelect.appendChild(option);

                    var selectedModeloId = @Model.ModeloId;

                    for (var i = 0; i < modeloSelect.options.length; i++) {
                        if (modeloSelect.options[i].value == selectedModeloId) {
                            modeloSelect.selectedIndex = i;
                            break;
                        }
                    }
                    var modeloId = modeloSelect.value;
                    var url = "/Autos/GetModeloById?modeloId=" + modeloId;

                    fetch(url)
                        .then(response => response.json())
                        .then(data => {
                            imagenauto.src = data;
                        })
                        .catch(error => console.log(error))
                });
            })
            .catch(error => console.log(error));
    }
</script>

Views/Autos/VerAutos.cshtml
@model IEnumerable<DALAUTOS.Model.Auto>
@using Microsoft.AspNetCore.Mvc.TagHelpers


@{
    ViewData["Title"] = "VerAutos";
}

<h1>Ver Autos</h1>

<form asp-action="VerAutos" method="get">
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="placas" placeholder="Filtrar por placas">
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Filtrar</button>
        </div>
    </div>
</form>


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-3">
            <div class="card" style="width: 18rem; position: relative;">
                <img src="@item.Marca.Logo" alt="Logo" class="logo-img">
                <img class="card-img-top fixed-size-img" src="@item.Modelo.Foto" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">@item.Modelo.Name</h5>
                    <h6 class="card-title">@item.Placas</h6>
                    <br>
                    @Html.DisplayFor(modelItem => item.status) status
                    <br>
                    <p class="card-text">@item.Color.NColor - @item.year</p>
                    <a class="btn btn-success" asp-controller="Autos" asp-action="EditarAuto" asp-route-id="@item.Id">Editar</a>
                    @*<a class="btn btn-warning" asp-action="Details" asp-route-id="@item.Id" asp-controller="Autos">Details</a>*@
                    <a class="btn btn-danger" asp-action="BorrarAuto" asp-route-id="@item.Id" asp-controller="Autos">Eliminar</a>
                </div>
            </div>
        </div>
    }
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#" onclick="changePage(@ViewBag.CurrentPage - 1)">Anterior</a></li>
        <li class="page-item"><a class="page-link" href="#" onclick="changePage(@ViewBag.CurrentPage + 1)">Siguente</a></li>
    </ul>
</nav>


<style>
    .logo-img {
        position: absolute;
        top: 10px;
        right: 10px;
        width: 40px;
        height: 40px;
    }

    .fixed-size-img {
        width: 100%;
        height: 200px;
        object-fit: cover;
    }
</style>

<script>
    function changePage(page) {
        window.location.href = '@Url.Action("VerAutos", "Autos")?page=' + page;
    }
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="https://cloudfront-eu-central-1.images.arcpublishing.com/diarioas/P52X3KT4VJGWTDNKLSVRR2WNUY.jpg" width="900" height="500" />
    <h1 class="display-4">Sistema de automoviles</h1>
    <p>Este es un sistema demostracion de CRUD de automoviles.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutosWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutosWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://media-rockstargames-com.akamaized.net/tina-uploads/posts/173494o83424ka/70a37850301fc7365e5ddb982831ff6ea394690e.jpg" width="70" height="50" style="border-radius: 50%;" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Informacion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autos" asp-action="VerAutos" asp-route-page="1">Ver Autos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autos" asp-action="CrearAuto">Registrar Auto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AutosWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>